- name: Install Docker and Run Nginx Container with Static Page
  hosts: docker_hosts
  become: true

  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present
      notify: Restart Docker

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Create directory for static site
      file:
        path: /opt/static-site
        state: directory
        mode: '0755'

    - name: Copy static index.html to host
      copy:
        src: files/index.html
        dest: /opt/static-site/index.html
      notify: Restart Nginx Container

    - name: Copy static index.html to host
      copy:
        src: files/index.html   # <-- place your index.html inside a 'files/' folder next to the playbook
        dest: /opt/static-site/index.html
      notify: Restart Nginx Container

    - name: Run Nginx container with mounted index.html
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /opt/static-site/index.html:/usr/share/nginx/html/index.html:ro

  handlers:
  - name: Restart Docker
    service:
      name: docker
      state: restarted

  - name: Restart Nginx Container
    community.docker.docker_container:
      name: nginx
      state: started
      restart: true

 




